#!/usr/bin/env ruby

# If installed as a gem, this won't do anything, however if we are
# working from the source, this will ensure our lib path is searched
# for require and include calls.
git_path = File.expand_path('../../.git', __FILE__)
if File.exist?(git_path)
  $:.unshift File.expand_path('../../lib', __FILE__)
end

require 'incline/cli'
Incline::CLI.new.execute(*ARGV)
