#!/usr/bin/env ruby

# If installed as a gem, this won't do anything, however if we are
# working from the source, this will ensure our lib path is searched
# for require and include calls.
git_path = File.expand_path('../../.git', __FILE__)
if File.exist?(git_path)
  $:.unshift File.expand_path('../../lib', __FILE__)
end

require 'incline/cli'

begin
  Incline::Cli.new(*ARGV).run
rescue Incline::Cli::CliError => e
  Incline::Cli.new(help_message: e.message).help
end


